# Extract Json Data

Process to extract json data:
1. Inspect url: https://www.theguardian.com/education/ng-interactive/2025/sep/13/the-guardian-university-guide-2026-the-rankings
2. Look under Networks
3. Re-fresh page and search under Fetch/XHR for json file
4. Run the code below using json url extracted from step 3

In [8]:
import pandas as pd
import requests

url = "https://interactive.guim.co.uk/atoms/labs/2025/09/university-guide/overview/v/1771858244880/assets/data/overview.json"
response = requests.get(url, timeout=30)
response.raise_for_status()
data = response.json()

universities = pd.DataFrame(data["institutions"])
universities

,institutionId,name,url,rank2026,rank2025,rank2024,guardianScore,percentSatisfiedWithTeaching,expenditurePerStudent,studentStaffRatio,careerProspects,valueAdded,averageEntryTariff,percentSatisfiedWithAssessment,continuation
0,0156,Oxford,https://www.theguardian.com/education/2009/may...,1,1.0,2.0,100,94,10,9.1,92,6.3,197,76,97.3
1,0173,St Andrews,https://www.theguardian.com/education/2009/may...,2,2.0,1.0,98.4,92.8,6.5,11,90,5.5,210,81.7,96.8
2,0114,Cambridge,https://www.theguardian.com/education/2009/may...,3,3.0,3.0,94.6,93.4,9.4,10.8,92,5.9,210,72.9,98.4
3,0137,London School of Economics,https://www.theguardian.com/education/2009/may...,4,4.0,4.0,93.8,89.4,8.7,11.4,93,5.9,185,76.2,96.4
4,0116,Durham,https://www.theguardian.com/education/2009/may...,5,6.0,7.0,85.5,90.5,6.4,12.4,89,6,180,81.6,96.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,0059,Greenwich,https://www.theguardian.com/education/2009/may...,119,117.0,116.0,38.5,84.6,3.5,16.9,75,5,108,82.2,84.6
119,0031,Roehampton,https://www.theguardian.com/education/2009/may...,120,110.0,111.0,36.3,84.6,4.8,20.9,67,3.9,94,82.8,87.5
120,0067,Middlesex,https://www.theguardian.com/education/2009/may...,121,113.0,115.0,36.1,87.1,None,17.4,69,5.9,103,84.3,78.8
121,0083,Westminster,https://www.theguardian.com/education/2009/may...,122,119.0,117.0,34.2,83.5,4.3,19.9,69,4.5,110,81.9,86.5
122,0105,West of Scotland,https://www.theguardian.com/education/2009/may...,123,121.0,119.0,28.6,89.5,2.8,19.2,74,5.9,138,86.1,77.9

## Extract Subject Areas
From data extract subject areas containing individual rankings for each area.

In [12]:
# Extract subject IDs and names for downloading individual subject rankings
subjects_data = [
    {
        "id": subject["id"],
        "title": subject["title"],
    }
    for subject in data.get("subjects", [])
    if subject.get("id") and subject.get("title")
]

subjects_data

[{'id': 'S250', 'title': 'Accounting and finance'},
 {'id': 'S195', 'title': 'Aerospace engineering'},
 {'id': 'S040', 'title': 'Anatomy and physiology'},
 {'id': 'S150', 'title': 'Animal science and agriculture'},
 {'id': 'S225', 'title': 'Animation and game design'},
 {'id': 'S325', 'title': 'Anthropology and archaeology'},
 {'id': 'S450', 'title': 'Architecture'},
 {'id': 'S100', 'title': 'Biology'},
 {'id': 'S045', 'title': 'Biomedical science'},
 {'id': 'S240', 'title': 'Business and management'},
 {'id': 'S170', 'title': 'Chemical engineering'},
 {'id': 'S110', 'title': 'Chemistry'},
 {'id': 'S053', 'title': "Children's nursing"},
 {'id': 'S200', 'title': 'Civil engineering'},
 {'id': 'S460', 'title': 'Classics and ancient history'},
 {'id': 'S220', 'title': 'Computer science and information systems'},
 {'id': 'S500', 'title': 'Construction, surveying and planning'},
 {'id': 'S385', 'title': 'Creative writing'},
 {'id': 'S315', 'title': 'Criminology'},
 {'id': 'S020', 'title': 'Dentistry'},
 {'id': 'S420', 'title': 'Drama and dance'},
 {'id': 'S140', 'title': 'Earth and marine sciences'},
 {'id': 'S360', 'title': 'Economics'},
 {'id': 'S290', 'title': 'Education'},
 {'id': 'S210', 'title': 'Electrical and electronic engineering'},
 {'id': 'S380', 'title': 'English'},
 {'id': 'S415', 'title': 'Fashion and textiles'},
 {'id': 'S430', 'title': 'Film production and photography'},
 {'id': 'S400', 'title': 'Fine art'},
 {'id': 'S120', 'title': 'Forensic science'},
 {'id': 'S160', 'title': 'General engineering'},
 {'id': 'S050', 'title': 'General nursing'},
 {'id': 'S270', 'title': 'Geography'},
 {'id': 'S410', 'title': 'Graphic design'},
 {'id': 'S070', 'title': 'Health professions'},
 {'id': 'S340', 'title': 'History'},
 {'id': 'S345', 'title': 'History of art'},
 {'id': 'S260', 'title': 'Hospitality, event management and tourism'},
 {'id': 'S411', 'title': 'Interior design'},
 {'id': 'S355', 'title': 'International relations'},
 {'id': 'S395', 'title': 'Journalism'},
 {'id': 'S370', 'title': 'Languages and linguistics'},
 {'id': 'S300', 'title': 'Law'},
 {'id': 'S245', 'title': 'Marketing and public relations'},
 {'id': 'S230', 'title': 'Mathematics'},
 {'id': 'S190', 'title': 'Mechanical engineering'},
 {'id': 'S390', 'title': 'Media and film studies'},
 {'id': 'S010', 'title': 'Medicine'},
 {'id': 'S052', 'title': 'Mental health nursing'},
 {'id': 'S054', 'title': 'Midwifery'},
 {'id': 'S440', 'title': 'Music'},
 {'id': 'S103', 'title': 'Nutrition and food science'},
 {'id': 'S072', 'title': 'Paramedic science'},
 {'id': 'S090', 'title': 'Pharmacy and pharmacology'},
 {'id': 'S470', 'title': 'Philosophy'},
 {'id': 'S130', 'title': 'Physics'},
 {'id': 'S073', 'title': 'Physiotherapy'},
 {'id': 'S350', 'title': 'Politics'},
 {'id': 'S412', 'title': 'Product design'},
 {'id': 'S080', 'title': 'Psychology'},
 {'id': 'S060', 'title': 'Social work'},
 {'id': 'S285', 'title': 'Sociology and social policy'},
 {'id': 'S490', 'title': 'Sports science'},
 {'id': 'S480', 'title': 'Theology and religious studies'},
 {'id': 'S030', 'title': 'Veterinary science'},
 {'id': 'S102', 'title': 'Zoology'}]

### Extract json data for individual subject areas

In [16]:
subject_dataframes = {}

base_url = "https://interactive.guim.co.uk/atoms/labs/2025/09/university-guide/overview/v/1771858244880/assets/data"

for subject in subjects_data:
    
    subject_id = subject["id"]
    subject_name = subject["title"]
    subject_url = f"{base_url}/{subject_id}.json"

    subject_response = requests.get(subject_url, timeout=30)
    subject_response.raise_for_status()
    subject_json = subject_response.json()

    records = subject_json.get("institutions", [])

    subject_dataframes[subject_id] = (
        pd.json_normalize(records)
        .assign(subject_id=subject_id, subject=subject_name)
    )

# Example: the DataFrame for subject S102
subject_dataframes["S102"]

,institutionId,name,url,courses,rank,guardianScore,percentSatisfiedWithTeaching,expenditurePerStudent,studentStaffRatio,careerProspects,valueAdded,averageEntryTariff,percentSatisfiedWithAssessment,continuation,subject_id,subject
0,0168,Glasgow,https://www.theguardian.com/education/2009/may...,[{'url': 'http://www.gla.ac.uk/undergraduate/d...,1,100,88.2,9.0,14.5,75.0,8.0,216,81.8,92.5,S102,Zoology
1,0112,Bristol,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.bristol.ac.uk/study/unde...,2,94.8,96.3,8.0,14.6,68.0,5.0,156,77,100,S102,Zoology
2,0105,West of Scotland,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.uws.ac.uk/study/undergra...,3,92.9,99.1,3.0,12,NaN,8.0,141,95.9,None,S102,Zoology
3,0180,Swansea,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.swansea.ac.uk/undergradu...,4,91,96.1,7.0,12.8,71.0,5.0,133,86.3,94.9,S102,Zoology
4,0119,Exeter,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.exeter.ac.uk/study/under...,5,83.8,84.5,6.0,12.3,71.0,8.0,151,70.7,93.2,S102,Zoology
5,0126,Liverpool,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.liverpool.ac.uk/courses/...,6,81.4,83.3,NaN,9,NaN,6.0,145,75.8,95.7,S102,Zoology
6,0066,Manchester Met,https://www.theguardian.com/education/2009/may...,[],7,81.3,None,4.0,15.6,NaN,8.0,129,None,91.5,S102,Zoology
7,0204,Manchester,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.manchester.ac.uk/study/u...,8,81.1,88.7,10.0,17.2,NaN,8.0,174,64.7,100,S102,Zoology
8,0062,Lincoln,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.lincoln.ac.uk/home/cours...,9,78,87.4,3.0,15.4,56.0,7.0,115,88.5,97.5,S102,Zoology
9,0155,Nottingham,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.nottingham.ac.uk/studywi...,10,76.9,80,9.0,12.1,NaN,6.0,150,74.4,94.1,S102,Zoology
10,0177,Aberystwyth,https://www.theguardian.com/education/2009/may...,[{'url': 'http://www.aber.ac.uk/courses/?7HUXJ...,11,74.3,91.4,NaN,9.6,64.0,5.0,116,82.8,90,S102,Zoology
11,0158,Salford,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.salford.ac.uk/courses/un...,12,74,88.9,4.0,16.7,55.0,9.0,117,84.2,89.8,S102,Zoology
12,0159,Sheffield,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.sheffield.ac.uk/undergra...,13,72.7,86.2,6.0,19.7,NaN,7.0,167,83.1,95.5,S102,Zoology
13,0170,Aberdeen,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.abdn.ac.uk/study/undergr...,14,72.1,90.3,7.0,19.1,74.0,7.0,178,79.7,92.4,S102,Zoology
14,0124,Leeds,https://www.theguardian.com/education/2009/may...,[{'url': 'https://courses.leeds.ac.uk/202526/3...,15,70.3,88.5,NaN,14.2,NaN,4.0,153,61.7,91.7,S102,Zoology
15,0162,Sussex,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.sussex.ac.uk/study/under...,16,70.1,78.9,9.0,16.2,NaN,7.0,135,72.6,94.7,S102,Zoology
16,0154,Newcastle,https://www.theguardian.com/education/2009/may...,[{'url': 'http://www.ncl.ac.uk/undergraduate/d...,17,69.9,83.8,6.0,18.5,76.0,8.0,124,67.1,96.4,S102,Zoology
17,0174,Stirling,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.stir.ac.uk/courses/ug/an...,18,65.5,79.8,7.0,14.4,NaN,2.0,179,77.7,94.4,S102,Zoology
18,0160,Southampton,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.southampton.ac.uk/course...,19,62.5,82.7,7.0,16,NaN,NaN,145,73.8,95.3,S102,Zoology
19,0184,"Queen's, Belfast",https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.qub.ac.uk/courses/underg...,20,61.7,88.2,5.0,14.7,NaN,5.0,160,78.9,89.3,S102,Zoology
20,0120,Hull,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.hull.ac.uk/study/undergr...,21,58.6,92.7,2.0,18.3,NaN,8.0,105,85.8,82.5,S102,Zoology
21,0038,Cumbria,https://www.theguardian.com/education/2009/may...,"[{'url': 'https://tinyurl.com/y5fsdhya', 'name...",22,57.5,92.3,2.0,20.5,NaN,8.0,108,86.9,89.6,S102,Zoology
22,0157,Reading,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.reading.ac.uk/ready-to-s...,23,52.2,89.7,5.0,24.4,72.0,6.0,112,78.7,93.7,S102,Zoology
23,0057,Derby,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.derby.ac.uk/undergraduat...,24,52,96.3,3.0,12.6,NaN,2.0,111,91.9,82.7,S102,Zoology
24,0047,Anglia Ruskin,https://www.theguardian.com/education/2009/may...,[{'url': 'https://aru.ac.uk/study/undergraduat...,25,51.7,93,5.0,12.6,60.0,3.0,97,87.5,82.4,S102,Zoology
25,0065,Liverpool John Moores,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.ljmu.ac.uk/study/courses...,26,51.1,82,3.0,15.7,55.0,3.0,123,83.6,91.9,S102,Zoology
26,0178,Bangor,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.bangor.ac.uk/courses/und...,27,44.1,83.5,3.0,18.4,56.0,3.0,128,70.1,94.6,S102,Zoology
27,0031,Roehampton,https://www.theguardian.com/education/2009/may...,[{'url': 'http://www.roehampton.ac.uk/undergra...,28,43.1,76.7,3.0,19.9,NaN,3.0,108,80,86.4,S102,Zoology
28,0073,Plymouth,https://www.theguardian.com/education/2009/may...,[{'url': 'https://www.plymouth.ac.uk/courses/u...,29,35,100,4.0,18.4,NaN,1.0,122,85,82.5,S102,Zoology